export const data = [
  {
    banner_metadata: {
      banner_id: 38917,
      campaign_unit_id: 38236,
      slot_id: 1,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/5b5de1582d99cbbe75a8f9a5c4dae1c2',
    image_hash: '5b5de1582d99cbbe75a8f9a5c4dae1c2',
    target_url: 'http://shopee.vn/m/don-dau-tien-mien-phi',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'http://shopee.vn/m/don-dau-tien-mien-phi',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39453,
      campaign_unit_id: 38699,
      slot_id: 2,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/39d1c464070be85f8b7a0d48c9a7c125',
    image_hash: '39d1c464070be85f8b7a0d48c9a7c125',
    target_url: 'https://shopee.vn/xiaomi-day',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/xiaomi-day',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39458,
      campaign_unit_id: 38703,
      slot_id: 3,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/32f1e4cc5c9506ea4a6be4d8a1bdbc41',
    image_hash: '32f1e4cc5c9506ea4a6be4d8a1bdbc41',
    target_url: 'https://shopee.vn/m/1010',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/m/1010',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39465,
      campaign_unit_id: 38711,
      slot_id: 4,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/fcdd62bca50c3138d89d91695f4a60cd',
    image_hash: 'fcdd62bca50c3138d89d91695f4a60cd',
    target_url: 'https://shopee.vn/m/top-deal-hot-trend',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/m/top-deal-hot-trend',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39466,
      campaign_unit_id: 38712,
      slot_id: 5,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/8ffa31fe4e5b226b823fe5ca102cac3a',
    image_hash: '8ffa31fe4e5b226b823fe5ca102cac3a',
    target_url: 'https://shopee.vn/sieu-sale-hb',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/sieu-sale-hb',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39468,
      campaign_unit_id: 38713,
      slot_id: 6,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/7ec24fd44b2348f33a062601aef32849',
    image_hash: '7ec24fd44b2348f33a062601aef32849',
    target_url: 'https://shopee.vn/m/freeship-xtra-plus',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/m/freeship-xtra-plus',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39470,
      campaign_unit_id: 38714,
      slot_id: 7,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/3fa8d40bac4eb28e8fe69d5b27b93295',
    image_hash: '3fa8d40bac4eb28e8fe69d5b27b93295',
    target_url: 'https://shopee.vn/m/danh-cho-ban-tre',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/m/danh-cho-ban-tre',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39471,
      campaign_unit_id: 38715,
      slot_id: 8,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/cb6609c5b07178d6f4b36c721b6fdcd4',
    image_hash: 'cb6609c5b07178d6f4b36c721b6fdcd4',
    target_url: 'https://shopee.vn/sieusale-hb',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/sieusale-hb',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39472,
      campaign_unit_id: 38716,
      slot_id: 9,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/fff54abedea1dbd2d27035ed6a1a5121',
    image_hash: 'fff54abedea1dbd2d27035ed6a1a5121',
    target_url: 'https://shopee.vn/beauty-club',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/beauty-club',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39473,
      campaign_unit_id: 38717,
      slot_id: 12,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/6ccd8793b7c41af4808b7f2997134d95',
    image_hash: '6ccd8793b7c41af4808b7f2997134d95',
    target_url: 'https://shopee.vn/skam-dien-tu',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/skam-dien-tu',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39494,
      campaign_unit_id: 38718,
      slot_id: 13,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/aa3454cffea909a308b937a56db1e65c',
    image_hash: 'aa3454cffea909a308b937a56db1e65c',
    target_url: 'https://shopee.vn/m/sale-hang-hieu-gia-tot',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/m/sale-hang-hieu-gia-tot',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39495,
      campaign_unit_id: 38719,
      slot_id: 14,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/ecdc119a693cca19833f63f07e231294',
    image_hash: 'ecdc119a693cca19833f63f07e231294',
    target_url: 'https://shopee.vn/shopeepayvn',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/shopeepayvn',
        image_width_percentage: 100,
      },
    ],
  },
  {
    banner_metadata: {
      banner_id: 39496,
      campaign_unit_id: 38720,
      slot_id: 15,
      source: 1,
      dl_json_data: '{"slot_tracking_id":0,"space_group_id":3}',
      tag: 0,
      team_id: 1,
    },
    image_url: 'https://cf.shopee.vn/file/c4c5b6a127a8aca43eade0952b49089e',
    image_hash: 'c4c5b6a127a8aca43eade0952b49089e',
    target_url: 'https://shopee.vn/ShopeeDoiXu',
    is_placeholder: false,
    number_of_sections: 1,
    click_sections: [
      {
        target_url: 'https://shopee.vn/ShopeeDoiXu',
        image_width_percentage: 100,
      },
    ],
  },
];
